a = {'alesound@gmail.com'=> ['ana.pelepka@gmail.com',
                        'brunakmuller@gmail.com',
                        'pcncastillo@hotmail.com',
                        'nicolas@touchtec.com.br',
                        'natguarana@gmail.com',
                        'caroline.lanfranchi@hotmail.com',
                        'andersonlfl@gmail.com',
                        'danilo.prinzio@consist.com.br',
                        'danidi01@yahoo.com.br',
                        'osvaldo.rein@consist.com.br',
                        'luiz@touchtec.com.br'],
 'altair.machado@consist.com.br'=> ['bclezar@gmail.com',
                                   'renata.bassi@caelum.com.br',
                                   'aparecida.bessa@gmail.com',
                                   'bielramires@gmail.com',
                                   'mlikoga@gmail.com',
                                   'fernandotakey@gmail.com',
                                   'libruck@yahoo.com.br',
                                   'andersonlfl@gmail.com',
                                   'rafael.rossi@yr.com',
                                   'lucasfcpoli@gmail.com',
                                   'franceline.franco@caelum.com.br'],
 'ana.pelepka@gmail.com'=> ['sara.cruz@kodak.com',
                           'renata.bassi@caelum.com.br',
                           'brunakmuller@gmail.com',
                           'deise@touchtec.com.br',
                           'natguarana@gmail.com',
                           'caroline.lanfranchi@hotmail.com',
                           'artur.polizel@gmail.com',
                           'danidi01@yahoo.com.br',
                           'guilherme.ztc@gmail.com',
                           'luiz@touchtec.com.br',
                           'roberto-alex@uol.com.br'],
 'anapatricia83@gmail.com'=> ['sara.cruz@kodak.com',
                             'dodsouza@gmail.com',
                             'renato.gallotti@consist.com.br',
                             'cesarwedemann@gmail.com',
                             'caroline.bessa@gmail.com',
                             'fabio.ortega@poli.usp.br',
                             'bruno.enomoto@gmail.com',
                             'bruno.doy@gmail.com',
                             'altair.machado@consist.com.br',
                             'saphyra.amaro@gmail.com',
                             'prm.pri@gmail.com'],
 'andersonlfl@gmail.com'=> ['aparecida.bessa@gmail.com',
                           'fernandotakey@gmail.com',
                           'lucasnapa@gmail.com',
                           'deise@touchtec.com.br',
                           'fabio.ortega@poli.usp.br',
                           'donizeti.andrade@consist.com.br',
                           'fabiohn@touchtec.com.br',
                           'alesound@gmail.com',
                           'altair.machado@consist.com.br',
                           'prm.pri@gmail.com',
                           'roberto-alex@uol.com.br'],
 'aparecida.bessa@gmail.com'=> ['renato.gallotti@consist.com.br',
                               'gabriela.arthur@yr.com',
                               'bielramires@gmail.com',
                               'deise@touchtec.com.br',
                               'graziele.grandi@caelum.com.br',
                               'pcncastillo@hotmail.com',
                               'vahidd@gmail.com',
                               'artur.polizel@gmail.com',
                               'alesound@gmail.com',
                               'rafael@touchtec.com.br',
                               'luiz@touchtec.com.br'],
 'artur.polizel@gmail.com'=> ['dodsouza@gmail.com',
                             'bclezar@gmail.com',
                             'silviatakey@gmail.com',
                             'rodolfo.j.souza@gmail.com',
                             'ana.pelepka@gmail.com',
                             'bielramires@gmail.com',
                             'fiuza_mari@yahoo.com.br',
                             'libruck@yahoo.com.br',
                             'donizeti.andrade@consist.com.br',
                             'danidi01@yahoo.com.br',
                             'rafael@touchtec.com.br'],
 'bclezar@gmail.com'=> ['donidi_jr@yahoo.com.br',
                       'silviatakey@gmail.com',
                       'mlikoga@gmail.com',
                       'fabio.ortega@poli.usp.br',
                       'nicolas@touchtec.com.br',
                       'caroline.lanfranchi@hotmail.com',
                       'donizeti.andrade@consist.com.br',
                       'alesound@gmail.com',
                       'rafael.rossi@yr.com',
                       'rafael@touchtec.com.br',
                       'luiz@touchtec.com.br'],
 'bessa.beatriz@gmail.com'=> ['fernandotakey@gmail.com',
                             'lucasnapa@gmail.com',
                             'deise@touchtec.com.br',
                             'graziele.grandi@caelum.com.br',
                             'danidi01@yahoo.com.br',
                             'lo.guarana@hotmail.com',
                             'rafael@touchtec.com.br',
                             'saphyra.amaro@gmail.com',
                             'prm.pri@gmail.com',
                             'roberto-alex@uol.com.br',
                             'franceline.franco@caelum.com.br'],
 'bielramires@gmail.com'=> ['aparecida.bessa@gmail.com',
                           'bessa.beatriz@gmail.com',
                           'brunakmuller@gmail.com',
                           'fernandotakey@gmail.com',
                           'lucasnapa@gmail.com',
                           'deise@touchtec.com.br',
                           'fiuza_mari@yahoo.com.br',
                           'libruck@yahoo.com.br',
                           'natguarana@gmail.com',
                           'alesound@gmail.com',
                           'lo.guarana@hotmail.com'],
 'brunakmuller@gmail.com'=> ['rjankauskas@hotmail.com',
                            'rodolfo.j.souza@gmail.com',
                            'mlikoga@gmail.com',
                            'caroline.bessa@gmail.com',
                            'fabio.ortega@poli.usp.br',
                            'fiuza_mari@yahoo.com.br',
                            'vahidd@gmail.com',
                            'rafinhacastillo@gmail.com',
                            'roberto-alex@uol.com.br'],
 'bruno.doy@gmail.com'=> ['cesarwedemann@gmail.com',
                         'gabriela.arthur@yr.com',
                         'lucasnapa@gmail.com',
                         'libruck@yahoo.com.br',
                         'pcncastillo@hotmail.com',
                         'natguarana@gmail.com',
                         'artur.polizel@gmail.com',
                         'rafael.rossi@yr.com',
                         'lucasfcpoli@gmail.com',
                         'saphyra.amaro@gmail.com',
                         'prm.pri@gmail.com'],
 'bruno.enomoto@gmail.com'=> ['dodsouza@gmail.com',
                             'rjankauskas@hotmail.com',
                             'bclezar@gmail.com',
                             'rodolfo.j.souza@gmail.com',
                             'graziele.grandi@caelum.com.br',
                             'camilo.rodegheri@gmail.com',
                             'anapatricia83@gmail.com',
                             'altair.machado@consist.com.br',
                             'luiz@touchtec.com.br',
                             'lucasfcpoli@gmail.com',
                             'prm.pri@gmail.com'],
 'camila.km@hotmail.com'=> ['rjankauskas@hotmail.com',
                           'renato.gallotti@consist.com.br',
                           'rodolfo.j.souza@gmail.com',
                           'mlikoga@gmail.com',
                           'lucasnapa@gmail.com',
                           'caroline.bessa@gmail.com',
                           'caroline.lanfranchi@hotmail.com',
                           'andersonlfl@gmail.com',
                           'alesound@gmail.com',
                           'osvaldo.rein@consist.com.br',
                           'altair.machado@consist.com.br'],
 'camilo.rodegheri@gmail.com'=> ['rjankauskas@hotmail.com',
                                'bclezar@gmail.com',
                                'renata.bassi@caelum.com.br',
                                'aparecida.bessa@gmail.com',
                                'pcncastillo@hotmail.com',
                                'vahidd@gmail.com',
                                'danidi01@yahoo.com.br'],
 'caroline.bessa@gmail.com'=> ['silviatakey@gmail.com',
                              'rodolfo.j.souza@gmail.com',
                              'ana.pelepka@gmail.com',
                              'libruck@yahoo.com.br',
                              'camilo.rodegheri@gmail.com',
                              'danilo.prinzio@consist.com.br',
                              'fabiohn@touchtec.com.br',
                              'bruno.doy@gmail.com',
                              'osvaldo.rein@consist.com.br',
                              'camila.km@hotmail.com',
                              'rafael@touchtec.com.br'],
 'caroline.lanfranchi@hotmail.com'=> ['donidi_jr@yahoo.com.br',
                                     'dodsouza@gmail.com',
                                     'renato.gallotti@consist.com.br',
                                     'caroline.bessa@gmail.com',
                                     'nicolas@touchtec.com.br',
                                     'artur.polizel@gmail.com',
                                     'fabiohn@touchtec.com.br',
                                     'lo.guarana@hotmail.com',
                                     'luiz@touchtec.com.br'],
 'cesarwedemann@gmail.com'=> ['camilo.rodegheri@gmail.com',
                             'pcncastillo@hotmail.com',
                             'caroline.lanfranchi@hotmail.com',
                             'donizeti.andrade@consist.com.br',
                             'danilo.prinzio@consist.com.br',
                             'fabiohn@touchtec.com.br',
                             'bruno.doy@gmail.com',
                             'anapatricia83@gmail.com',
                             'camila.km@hotmail.com'],
 'danidi01@yahoo.com.br'=> ['silviatakey@gmail.com',
                           'aparecida.bessa@gmail.com',
                           'bessa.beatriz@gmail.com',
                           'brunakmuller@gmail.com',
                           'fernandotakey@gmail.com',
                           'deise@touchtec.com.br',
                           'bruno.enomoto@gmail.com',
                           'rafinhacastillo@gmail.com',
                           'alesound@gmail.com',
                           'prm.pri@gmail.com',
                           'roberto-alex@uol.com.br'],
 'danilo.prinzio@consist.com.br'=> ['renata.bassi@caelum.com.br',
                                   'aparecida.bessa@gmail.com',
                                   'cesarwedemann@gmail.com',
                                   'bielramires@gmail.com',
                                   'caroline.bessa@gmail.com',
                                   'fabio.ortega@poli.usp.br',
                                   'fabiohn@touchtec.com.br',
                                   'guilherme.ztc@gmail.com',
                                   'saphyra.amaro@gmail.com'],
 'deise@touchtec.com.br'=> ['silviatakey@gmail.com',
                         'diegolopesesteves@gmail.com',
                         'gabriela.arthur@yr.com',
                         'fabio.ortega@poli.usp.br',
                         'fiuza_mari@yahoo.com.br',
                         'bruno.enomoto@gmail.com',
                         'donizeti.andrade@consist.com.br',
                         'rafinhacastillo@gmail.com',
                         'camila.km@hotmail.com',
                         'rafael.rossi@yr.com',
                         'guilherme.ztc@gmail.com'],
 'diegolopesesteves@gmail.com'=> ['sara.cruz@kodak.com',
                                 'rjankauskas@hotmail.com',
                                 'renato.gallotti@consist.com.br',
                                 'deise@touchtec.com.br',
                                 'nicolas@touchtec.com.br',
                                 'lo.guarana@hotmail.com',
                                 'osvaldo.rein@consist.com.br',
                                 'saphyra.amaro@gmail.com'],
 'dodsouza@gmail.com'=> ['gabriela.arthur@yr.com',
                        'libruck@yahoo.com.br',
                        'camilo.rodegheri@gmail.com',
                        'pcncastillo@hotmail.com',
                        'caroline.lanfranchi@hotmail.com'],
 'donidi_jr@yahoo.com.br'=> ['diegolopesesteves@gmail.com',
                            'bielramires@gmail.com',
                            'mlikoga@gmail.com',
                            'pcncastillo@hotmail.com',
                            'vahidd@gmail.com',
                            'rafinhacastillo@gmail.com',
                            'lo.guarana@hotmail.com',
                            'camila.km@hotmail.com',
                            'lucasfcpoli@gmail.com',
                            'saphyra.amaro@gmail.com',
                            'roberto-alex@uol.com.br'],
 'donizeti.andrade@consist.com.br'=> ['bclezar@gmail.com',
                                     'rodolfo.j.souza@gmail.com',
                                     'diegolopesesteves@gmail.com',
                                     'mlikoga@gmail.com',
                                     'graziele.grandi@caelum.com.br',
                                     'camilo.rodegheri@gmail.com',
                                     'vahidd@gmail.com',
                                     'andersonlfl@gmail.com',
                                     'camila.km@hotmail.com',
                                     'rafael.rossi@yr.com',
                                     'roberto-alex@uol.com.br'],
 'fabio.ortega@poli.usp.br'=> ['donidi_jr@yahoo.com.br',
                              'sara.cruz@kodak.com',
                              'aparecida.bessa@gmail.com',
                              'cesarwedemann@gmail.com',
                              'ana.pelepka@gmail.com',
                              'bessa.beatriz@gmail.com',
                              'brunakmuller@gmail.com',
                              'nicolas@touchtec.com.br',
                              'donizeti.andrade@consist.com.br',
                              'fabiohn@touchtec.com.br',
                              'prm.pri@gmail.com'],
 'fabiohn@touchtec.com.br'=> ['donidi_jr@yahoo.com.br',
                             'sara.cruz@kodak.com',
                             'dodsouza@gmail.com',
                             'caroline.bessa@gmail.com',
                             'fabio.ortega@poli.usp.br',
                             'altair.machado@consist.com.br',
                             'lucasfcpoli@gmail.com'],
 'fernandotakey@gmail.com'=> ['renata.bassi@caelum.com.br',
                             'cesarwedemann@gmail.com',
                             'diegolopesesteves@gmail.com',
                             'graziele.grandi@caelum.com.br',
                             'fiuza_mari@yahoo.com.br',
                             'libruck@yahoo.com.br',
                             'natguarana@gmail.com',
                             'anapatricia83@gmail.com',
                             'guilherme.ztc@gmail.com',
                             'luiz@touchtec.com.br',
                             'franceline.franco@caelum.com.br'],
 'fiuza_mari@yahoo.com.br'=> ['diegolopesesteves@gmail.com',
                             'ana.pelepka@gmail.com',
                             'graziele.grandi@caelum.com.br',
                             'camilo.rodegheri@gmail.com',
                             'andersonlfl@gmail.com',
                             'alesound@gmail.com',
                             'rafael.rossi@yr.com',
                             'rafael@touchtec.com.br',
                             'lucasfcpoli@gmail.com',
                             'roberto-alex@uol.com.br',
                             'franceline.franco@caelum.com.br'],
 'franceline.franco@caelum.com.br'=> ['silviatakey@gmail.com',
                                     'cesarwedemann@gmail.com',
                                     'bielramires@gmail.com',
                                     'brunakmuller@gmail.com',
                                     'fabio.ortega@poli.usp.br',
                                     'fiuza_mari@yahoo.com.br',
                                     'camilo.rodegheri@gmail.com',
                                     'pcncastillo@hotmail.com',
                                     'fabiohn@touchtec.com.br',
                                     'rafael@touchtec.com.br',
                                     'roberto-alex@uol.com.br'],
 'gabriela.arthur@yr.com'=> ['donidi_jr@yahoo.com.br',
                            'sara.cruz@kodak.com',
                            'renata.bassi@caelum.com.br',
                            'cesarwedemann@gmail.com',
                            'bielramires@gmail.com',
                            'caroline.bessa@gmail.com',
                            'nicolas@touchtec.com.br',
                            'artur.polizel@gmail.com',
                            'donizeti.andrade@consist.com.br',
                            'danilo.prinzio@consist.com.br',
                            'saphyra.amaro@gmail.com'],
 'graziele.grandi@caelum.com.br'=> ['rodolfo.j.souza@gmail.com',
                                   'fernandotakey@gmail.com',
                                   'lucasnapa@gmail.com',
                                   'nicolas@touchtec.com.br',
                                   'fabiohn@touchtec.com.br',
                                   'bruno.doy@gmail.com',
                                   'anapatricia83@gmail.com',
                                   'guilherme.ztc@gmail.com'],
 'guilherme.ztc@gmail.com'=> ['renato.gallotti@consist.com.br',
                             'graziele.grandi@caelum.com.br',
                             'caroline.lanfranchi@hotmail.com',
                             'lo.guarana@hotmail.com',
                             'bruno.doy@gmail.com',
                             'osvaldo.rein@consist.com.br',
                             'rafael@touchtec.com.br',
                             'roberto-alex@uol.com.br'],
 'libruck@yahoo.com.br'=> ['donidi_jr@yahoo.com.br',
                          'rjankauskas@hotmail.com',
                          'cesarwedemann@gmail.com',
                          'deise@touchtec.com.br',
                          'danilo.prinzio@consist.com.br',
                          'anapatricia83@gmail.com',
                          'osvaldo.rein@consist.com.br',
                          'lucasfcpoli@gmail.com'],
 'lo.guarana@hotmail.com'=> ['renato.gallotti@consist.com.br',
                            'renata.bassi@caelum.com.br',
                            'gabriela.arthur@yr.com',
                            'ana.pelepka@gmail.com',
                            'fernandotakey@gmail.com',
                            'bruno.enomoto@gmail.com',
                            'osvaldo.rein@consist.com.br',
                            'altair.machado@consist.com.br'],
 'lucasfcpoli@gmail.com'=> ['donidi_jr@yahoo.com.br',
                           'rjankauskas@hotmail.com',
                           'ana.pelepka@gmail.com',
                           'bessa.beatriz@gmail.com',
                           'fiuza_mari@yahoo.com.br',
                           'pcncastillo@hotmail.com',
                           'bruno.enomoto@gmail.com',
                           'fabiohn@touchtec.com.br',
                           'bruno.doy@gmail.com',
                           'camila.km@hotmail.com',
                           'rafael@touchtec.com.br'],
 'lucasnapa@gmail.com'=> ['bclezar@gmail.com',
                         'silviatakey@gmail.com',
                         'rodolfo.j.souza@gmail.com',
                         'caroline.bessa@gmail.com',
                         'vahidd@gmail.com',
                         'caroline.lanfranchi@hotmail.com',
                         'danilo.prinzio@consist.com.br',
                         'saphyra.amaro@gmail.com'],
 'luiz@touchtec.com.br'=> ['sara.cruz@kodak.com',
                          'dodsouza@gmail.com',
                          'rjankauskas@hotmail.com',
                          'silviatakey@gmail.com',
                          'aparecida.bessa@gmail.com',
                          'bessa.beatriz@gmail.com',
                          'caroline.lanfranchi@hotmail.com',
                          'rafinhacastillo@gmail.com',
                          'saphyra.amaro@gmail.com',
                          'prm.pri@gmail.com',
                          'franceline.franco@caelum.com.br'],
 'mlikoga@gmail.com'=> ['bclezar@gmail.com',
                       'brunakmuller@gmail.com',
                       'fernandotakey@gmail.com',
                       'vahidd@gmail.com',
                       'natguarana@gmail.com',
                       'artur.polizel@gmail.com',
                       'danidi01@yahoo.com.br',
                       'lo.guarana@hotmail.com',
                       'rafael.rossi@yr.com',
                       'guilherme.ztc@gmail.com',
                       'franceline.franco@caelum.com.br'],
 'natguarana@gmail.com'=> ['donidi_jr@yahoo.com.br',
                          'sara.cruz@kodak.com',
                          'ana.pelepka@gmail.com',
                          'lucasnapa@gmail.com',
                          'deise@touchtec.com.br',
                          'fabio.ortega@poli.usp.br',
                          'bruno.enomoto@gmail.com',
                          'caroline.lanfranchi@hotmail.com',
                          'rafinhacastillo@gmail.com',
                          'anapatricia83@gmail.com',
                          'altair.machado@consist.com.br'],
 'nicolas@touchtec.com.br'=> ['renato.gallotti@consist.com.br',
                             'diegolopesesteves@gmail.com',
                             'lucasnapa@gmail.com',
                             'natguarana@gmail.com',
                             'andersonlfl@gmail.com',
                             'artur.polizel@gmail.com',
                             'danilo.prinzio@consist.com.br',
                             'rafinhacastillo@gmail.com',
                             'danidi01@yahoo.com.br',
                             'anapatricia83@gmail.com',
                             'altair.machado@consist.com.br'],
 'osvaldo.rein@consist.com.br'=> ['dodsouza@gmail.com',
                                 'rodolfo.j.souza@gmail.com',
                                 'cesarwedemann@gmail.com',
                                 'caroline.bessa@gmail.com',
                                 'fiuza_mari@yahoo.com.br',
                                 'nicolas@touchtec.com.br',
                                 'fabiohn@touchtec.com.br',
                                 'camila.km@hotmail.com',
                                 'rafael.rossi@yr.com',
                                 'lucasfcpoli@gmail.com'],
 'pcncastillo@hotmail.com'=> ['sara.cruz@kodak.com',
                             'diegolopesesteves@gmail.com',
                             'ana.pelepka@gmail.com',
                             'mlikoga@gmail.com',
                             'brunakmuller@gmail.com',
                             'caroline.bessa@gmail.com',
                             'camilo.rodegheri@gmail.com',
                             'andersonlfl@gmail.com',
                             'lo.guarana@hotmail.com',
                             'anapatricia83@gmail.com',
                             'lucasfcpoli@gmail.com'],
 'prm.pri@gmail.com'=> ['bessa.beatriz@gmail.com',
                       'brunakmuller@gmail.com',
                       'fernandotakey@gmail.com',
                       'graziele.grandi@caelum.com.br',
                       'pcncastillo@hotmail.com',
                       'vahidd@gmail.com',
                       'natguarana@gmail.com',
                       'danidi01@yahoo.com.br',
                       'bruno.doy@gmail.com',
                       'osvaldo.rein@consist.com.br',
                       'luiz@touchtec.com.br'],
 'rafael.rossi@yr.com'=> ['donidi_jr@yahoo.com.br',
                         'dodsouza@gmail.com',
                         'rjankauskas@hotmail.com',
                         'cesarwedemann@gmail.com',
                         'bielramires@gmail.com',
                         'brunakmuller@gmail.com',
                         'andersonlfl@gmail.com',
                         'rafinhacastillo@gmail.com',
                         'lo.guarana@hotmail.com',
                         'osvaldo.rein@consist.com.br',
                         'altair.machado@consist.com.br'],
 'rafael@touchtec.com.br'=> ['dodsouza@gmail.com',
                            'renata.bassi@caelum.com.br',
                            'gabriela.arthur@yr.com',
                            'libruck@yahoo.com.br',
                            'bruno.enomoto@gmail.com'],
 'rafinhacastillo@gmail.com'=> ['rjankauskas@hotmail.com',
                               'bclezar@gmail.com',
                               'bessa.beatriz@gmail.com',
                               'graziele.grandi@caelum.com.br',
                               'camilo.rodegheri@gmail.com',
                               'nicolas@touchtec.com.br',
                               'donizeti.andrade@consist.com.br',
                               'alesound@gmail.com',
                               'bruno.doy@gmail.com',
                               'guilherme.ztc@gmail.com',
                               'saphyra.amaro@gmail.com'],
 'renata.bassi@caelum.com.br'=> ['dodsouza@gmail.com',
                                'bclezar@gmail.com',
                                'gabriela.arthur@yr.com',
                                'vahidd@gmail.com',
                                'bruno.doy@gmail.com'],
 'renato.gallotti@consist.com.br'=> ['silviatakey@gmail.com',
                                    'diegolopesesteves@gmail.com',
                                    'mlikoga@gmail.com',
                                    'lucasnapa@gmail.com',
                                    'bruno.enomoto@gmail.com',
                                    'donizeti.andrade@consist.com.br',
                                    'rafinhacastillo@gmail.com',
                                    'alesound@gmail.com',
                                    'anapatricia83@gmail.com',
                                    'camila.km@hotmail.com',
                                    'guilherme.ztc@gmail.com'],
 'rjankauskas@hotmail.com'=> ['silviatakey@gmail.com',
                             'gabriela.arthur@yr.com',
                             'bessa.beatriz@gmail.com',
                             'mlikoga@gmail.com',
                             'deise@touchtec.com.br',
                             'rafinhacastillo@gmail.com',
                             'danidi01@yahoo.com.br',
                             'rafael.rossi@yr.com'],
 'roberto-alex@uol.com.br'=> ['diegolopesesteves@gmail.com',
                             'gabriela.arthur@yr.com',
                             'ana.pelepka@gmail.com',
                             'bessa.beatriz@gmail.com',
                             'bielramires@gmail.com',
                             'fabio.ortega@poli.usp.br',
                             'graziele.grandi@caelum.com.br',
                             'andersonlfl@gmail.com',
                             'artur.polizel@gmail.com',
                             'danilo.prinzio@consist.com.br',
                             'camila.km@hotmail.com'],
 'rodolfo.j.souza@gmail.com'=> ['bclezar@gmail.com',
                               'renata.bassi@caelum.com.br',
                               'fernandotakey@gmail.com',
                               'camilo.rodegheri@gmail.com',
                               'artur.polizel@gmail.com',
                               'donizeti.andrade@consist.com.br',
                               'danilo.prinzio@consist.com.br',
                               'lo.guarana@hotmail.com',
                               'anapatricia83@gmail.com',
                               'luiz@touchtec.com.br',
                               'prm.pri@gmail.com'],
 'saphyra.amaro@gmail.com'=> ['aparecida.bessa@gmail.com',
                             'diegolopesesteves@gmail.com',
                             'gabriela.arthur@yr.com',
                             'bessa.beatriz@gmail.com',
                             'bielramires@gmail.com',
                             'fiuza_mari@yahoo.com.br',
                             'vahidd@gmail.com',
                             'natguarana@gmail.com',
                             'camila.km@hotmail.com',
                             'rafael.rossi@yr.com',
                             'franceline.franco@caelum.com.br'],
 'sara.cruz@kodak.com'=> ['renato.gallotti@consist.com.br',
                         'fiuza_mari@yahoo.com.br',
                         'nicolas@touchtec.com.br',
                         'bruno.enomoto@gmail.com',
                         'danidi01@yahoo.com.br',
                         'bruno.doy@gmail.com',
                         'osvaldo.rein@consist.com.br',
                         'altair.machado@consist.com.br',
                         'luiz@touchtec.com.br',
                         'lucasfcpoli@gmail.com',
                         'franceline.franco@caelum.com.br'],
 'silviatakey@gmail.com'=> ['sara.cruz@kodak.com',
                           'rodolfo.j.souza@gmail.com',
                           'aparecida.bessa@gmail.com',
                           'lucasnapa@gmail.com',
                           'libruck@yahoo.com.br',
                           'bruno.enomoto@gmail.com',
                           'andersonlfl@gmail.com',
                           'artur.polizel@gmail.com',
                           'danilo.prinzio@consist.com.br',
                           'guilherme.ztc@gmail.com',
                           'franceline.franco@caelum.com.br'],
 'vahidd@gmail.com'=> ['donidi_jr@yahoo.com.br',
                      'renato.gallotti@consist.com.br',
                      'renata.bassi@caelum.com.br',
                      'mlikoga@gmail.com',
                      'libruck@yahoo.com.br',
                      'natguarana@gmail.com',
                      'alesound@gmail.com',
                      'guilherme.ztc@gmail.com',
                      'rafael@touchtec.com.br',
                      'prm.pri@gmail.com',
                      'franceline.franco@caelum.com.br']}
                     
a.each_pair do |email,list|
 sender = User.find_by_email(email)
 list.each do |stranger|                 
   target = User.find_by_email(stranger)
   RecommendationGuide.create :sender_id => sender, :target_id => target, :times => 1
 end 
end